import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my projects',
  projects: [
    {
      id: getId(),
      name: 'Karni',
      url: 'https://karny.ma/fr',
      img: '/projects/karni.png',
      year: 2024,
      tags: ['Mobile App', 'React Native', 'Node.js', 'MongoDB'],
    },
    {
      id: getId(),
      name: 'Express Relais',
      url: 'https://expressrelais.ma/',
      img: '/projects/express.png',
      year: 2025,
      tags: ['Vue.js', 'Node.js', 'MongoDB', 'Docker'],
    },
    {
      id: getId(),
      name: 'Squarefeet CRM',
      url: 'https://www.squarefeet.cloud/fr/accueil/',
      img: '/projects/squarefeet.png',
      year: 2025,
      tags: ['Vue.js', 'React', 'NestJS', 'GraphQL'],
    },
    {
      id: getId(),
      name: 'Authentikeys E-commerce',
      url: 'https://www.authentikeys.com',
      img: '/projects/authentikeys.png',
      year: 2024,
      tags: ['React', 'Next.js', 'Node.js', 'MongoDB'],
    },
    {
      id: getId(),
      name: 'KIIIBS - Keyboard Store',
      url: 'https://ecomy-alpha.vercel.app',
      repo: 'https://github.com/REDWANE-AIT-OUKAZZAMANE/Ecomy',
      img: '/projects/Keyboard-ecom.png',
      year: 2023,
      tags: ['Vue.js', 'TypeScript', 'Tailwind', 'Pinia'],
    },
    {
      id: getId(),
      name: 'SWAG - 3D Racing Game',
      url: 'https://swag-hazel.vercel.app',
      repo: 'https://github.com/REDWANE-AIT-OUKAZZAMANE/swag',
      img: '/projects/game.png',
      year: 2023,
      tags: ['Three.js', 'JavaScript', 'HTML/CSS'],
    },
    {
      id: getId(),
      name: '3D House Visualization',
      url: 'https://vercel.com/redwane-ait-oukazzamanes-projects/3d-house',
      repo: 'https://github.com/REDWANE-AIT-OUKAZZAMANE/3d-house',
      img: '/projects/house.png',
      year: 2022,
      tags: ['Three.js', 'JavaScript', 'GSAP'],
    },
    {
      id: getId(),
      name: 'IT Support System',
      repo: 'https://github.com/REDWANE-AIT-OUKAZZAMANE/it-support-system',
      img: '/projects/itSupport.png',
      year: 2022,
      tags: ['Java', 'Spring Boot', 'Oracle DB', 'Docker'],
    },
    {
      id: getId(),
      name: 'Weather Dashboard',
      url: 'https://weather-app-phi-nine-54.vercel.app/',
      repo: 'https://github.com/REDWANE-AIT-OUKAZZAMANE/weather-app',
      img: '/projects/weather.png',
      year: 2021,
      tags: ['JavaScript', 'HTML/CSS', 'API'],
    },
  ],
};
